# Allow kube-rbac-proxies to create tokenreviews and subjectaccessreviews to check Prometheus identity when scraping metrics.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vmware-vsphere-kube-rbac-proxy-binding
subjects:
  - kind: ServiceAccount
    name: vmware-vsphere-csi-driver-controller-sa
    namespace: openshift-cluster-csi-drivers
  - kind: ServiceAccount
    name: vmware-vsphere-csi-driver-operator
    namespace: openshift-cluster-csi-drivers
roleRef:
  kind: ClusterRole
  name: vmware-vsphere-kube-rbac-proxy-role
  apiGroup: rbac.authorization.k8s.io
