# Allow kube-rbac-proxies to create tokenreviews and subjectaccessreviews to check Prometheus identity when scraping metrics.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vmware-vsphere-kube-rbac-proxy-role
rules:
  - apiGroups:
    - "authentication.k8s.io"
    resources:
    - "tokenreviews"
    verbs:
    - "create"
  - apiGroups:
    - "authorization.k8s.io"
    resources:
    - "subjectaccessreviews"
    verbs:
    - "create"
