apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.vsphere.vmware.com
  annotations:
    # Used to determine if a CSI driver was created by OCP or by 3rd party operator / helm / yaml files.
    csi.openshift.io/managed: "true"
spec:
  attachRequired: true
  podInfoOnMount: false
  fsGroupPolicy: File
  requiresRepublish: false
  storageCapacity: false
  volumeLifecycleModes:
    - Persistent
